import Header from "@/components/Header/Hearder";
import NewItemController from "@/components/NewItem/Controller";
import { Box, Container } from "@mui/system";
import { NextPage } from "next";
import Head from "next/head";

const HomePage: NextPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>My Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <NewItemController />
        </Box>
      </Container>
    </>
  );
};
export default HomePage;
