import Header from "@/components/Header/Header";
import NewItemController from "@/components/NewItem/Controller";
import getUser from "@/services/user/getUser";
import { Container } from "@mui/system";
import { NextPage, GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { parseCookies } from "nookies";

const HomePage: NextPage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>My Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header username={data.username} />
      <Container>
        <NewItemController />
      </Container>
    </>
  );
};
export default HomePage;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { "auth.token": token, "userid.token": tokenId } = parseCookies(ctx);
  if (!token || !tokenId) {
    return {
      redirect: {
        permanent: false,
        destination: "/signin",
      },
    };
  }
  const data = await getUser({ id: tokenId });
  return {
    props: { data },
  };
};
